### ISSUE TITLE
Failed to run demo-a3-headless after apostrophe update on 3.0.0-aplha.3 version

### ISSUE THREAD

**Issue by nikolalakovic85** [apostrophecms/demo-a3-headless#1]
## To Reproduce

> 1. Go to this repo and download it to your local machine
> 2. Install dependencies
> 3. Start demo with "yarn dev" (if you're using yarn) or "npm run dev"
> 4. You will get OperationalError: ./node_modules/lowlight/lib/core.js
Module not found: Error: Can't resolve 'highlight.js/lib/core' in '/Users/nikolalakovic/Documents/sitestorm/demo-a3-headless/node_modules/lowlight/lib'
>5. After manual installation of 'lowlight' library (yarn add lowlight) everything is fine

**Comment by abea** [comment]
You're right. This is only happening with yarn, for reasons I don't fully understand, but assume it's to do with how yarn handles dependencies. I'll add that module to this demo's dependencies to resolve that for now.

It looks like this is related to our instance of Storybook (a UI component library), which will be removed from core at some point before stable release anyway.

Thanks for flagging this issue!

**Comment by abea** [comment]
Today's update in #4 the lowlight dependency was removed since `3.0.0-alpha.4` no longer has Storybook as a dependency.
